[general]
working_directory = "./workspace"
import = []

[window]
decorations = "Full"
blur = true
opacity = 0.97
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"
decorations_theme_variant = "Dark"
resize_increments = true

[terminal.shell]
program = "/home/linuxbrew/.linuxbrew/bin/bash"
args = ["-l"]

[font]
size = 14
normal.family = "MesloLGL Nerd Font"
offset.y = 2
glyph_offset.y = 1
# force italics to be displayed as regular font
italic.style = "Regular"
bold_italic.style = "Bold"

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Block"
style.blinking = "Always"
blink_interval = 400
blink_timeout = 0

[mouse]
hide_when_typing = false

[scrolling]
history = 100000
multiplier = 3

[keyboard]
bindings = [
    { key = "F11", action = "ToggleFullscreen" },
    { key = "F12", action = "Minimize" },
]
